//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

= Configurando o Banco de Dados =

O próximo passo crucial após a criação de um projeto Django é configurar o banco de dados. O Django oferece suporte a vários backends de banco de dados, e para começar, usaremos o SQLite, que é um banco de dados leve e embutido por padrão.

=== Abra o Arquivo settings.py ===

O arquivo `settings.py` no diretório principal do seu projeto contém as configurações principais do Django, incluindo a configuração do banco de dados.

=== Localize a Seção de Configuração do Banco de Dados ===

Dentro do arquivo settings.py, você encontrará uma seção chamada `DATABASES`. Por padrão, ele está configurado para usar o SQLite. Veja um exemplo básico:

[source, python]
----
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}
----

- ENGINE: Especifica o backend do banco de dados a ser usado. Neste exemplo, estamos usando o SQLite.
- NAME: Indica o caminho para o arquivo do banco de dados. Neste caso, ele é criado no diretório do projeto com o nome db.sqlite3.

=== Configurações Adicionais (Opcional) ===

Você pode precisar ajustar as configurações do banco de dados conforme necessário para atender aos requisitos específicos do seu projeto. Por exemplo, se estiver usando um banco de dados diferente, como `PostgreSQL` ou `MySQL`, você precisará fornecer informações adicionais, como nome do usuário, senha, host, etc.

==== Exemplo com PostgreSQL: ====

[source, python]
----
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'nomedobanco',
        'USER': 'seuusuario',
        'PASSWORD': 'suasenha',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
----

==== Exemplo com MySQL: ====

[source, python]
----
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'nomedobanco',
        'USER': 'seuusuario',
        'PASSWORD': 'suasenha',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}
----

=== Aplicando Migrações ===

Após configurar o banco de dados, você precisa aplicar as migrações para criar as tabelas necessárias no banco de dados. No terminal, dentro do diretório do seu projeto, execute:

[source, cmd]
----
python manage.py migrate
----

Este comando criará as tabelas padrão do Django no banco de dados configurado.


link:https://hemmerson.github.io/django-aula/[HOME]