//caminho padrão para imagens
:imagesdir: images
:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

//Estilo do Sumário
:toc2: 
//após os : insere o texto que deseja ser visível
:toc-title: Sumário
:figure-caption: Figura
//numerar titulos
:numbered:
:source-highlighter: highlightjs
:icons: font
:chapter-label:
:doctype: book
:lang: pt-BR
//3+| mesclar linha tabela

= Criando Views, Forms, URLs e Templates de Pessoa Jurídica =

== Criando Form ==

=== Entendendo a Estrutura de Form em Django ===

Em Django, os formulários (`Form`) desempenham um papel crucial na interação com o usuário e na coleta de dados. Eles são usados para criar, validar e processar dados submetidos pelo usuário. Nesta seção, exploraremos a estrutura fundamental dos formulários em Django.

==== O que são Formulários em Django? ====

Os formulários em Django são classes Python que definem como os dados do usuário serão coletados e processados no servidor. Eles fornecem uma camada de abstração sobre o HTML e ajudam a lidar com a validação de dados de maneira eficiente.

==== Componentes Essenciais de um Formulário ====

Ao trabalhar com formulários em Django, é fundamental compreender os seguintes componentes:

    1. Campos (Fields):
        - Representam os diferentes campos de dados que um usuário pode preencher (por exemplo, texto, número, e-mail).
        - Cada campo em um formulário é representado por uma instância de uma classe de campo específica.

    2. Widgets:
        - Controlam a aparência e o comportamento visual dos campos em um formulário.
        - Determinam como os campos serão exibidos no navegador do usuário.

    3. Validação:
        - Garante que os dados fornecidos pelos usuários atendam aos requisitos especificados.
        - A validação é realizada automaticamente pelo Django, mas você também pode adicionar validações personalizadas conforme necessário.

    4. Renderização de Formulários:
        - Transforma a definição do formulário em HTML para ser exibido em uma página da web.
        - O Django fornece funcionalidades integradas para renderizar formulários, mas você pode personalizar a renderização conforme necessário.


=== Estrutura do Form para o Model PessoaJuridica ===

.forms.py
[source, python]
----
from django import forms
from .models import PessoaJuridica

class PessoaJuridicaForm(forms.ModelForm):
    class Meta:
        model = PessoaJuridica
        fields = '__all__'
        widgets = {
            'nome':forms.TextInput(attrs={
                'class':'form-control',
                'required':'required',
            }),
            'email':forms.EmailInput(attrs={
                'class':'form-control',
                'required':'required',
            }),
            'cnpj':forms.TextInput(attrs={
                'class':'form-control',
                'required':'required',
            }),
            'razao_social':forms.TextInput(attrs={
                'class':'form-control',
                'required':'required',
            }),
        }
----

Este `Form` cria um tipo de ligação do HTML com a view que o chamou.

== Criando Views == 

=== Criando Views para Listar, Criar, Atualizar e Excluir Registros: ===

.view para PessoaJuridica método 2
[source, python]
----
from django.shortcuts import render, redirect, get_object_or_404
from .models import PessoaJuridica
from .forms import PessoaJuridicaForm

def index(request):
    return render(request, "index.html")

#========================= Pessoa Jurídica ================================

def listaPessoaJuridica(request):
    listaPJ = PessoaJuridica.objects.all()
    return render(request, 'pj_list.html', {'listapessoajuridica': listaPJ})

def novoPessoaJuridica(request):
    if request.method == 'POST':
        form = PessoaJuridicaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(listaPessoaJuridica)
    
    else:
        form = PessoaJuridicaForm()
    return render(request, 'pj_form.html', {'form':form})

def updatePessoaJuridica(request, id):
    pessoaJuridica = get_object_or_404(PessoaJuridica, id = id)

    if request.method == 'POST':
        form = PessoaJuridicaForm(request.POST, instance=pessoaJuridica)
        if form.is_valid():
            form.save()
            return redirect(listaPessoaJuridica)
    else:
        form = PessoaJuridicaForm(instance=pessoaJuridica)
    
    return render(request, 'pj_form.html', {'form':form, 'pessoa_juridica':pessoaJuridica})

def deletePessoaJuridica(request, id):
    pessoaJuridica = get_object_or_404(PessoaJuridica, id = id)

    if request.method == 'POST':
        pessoaJuridica.delete()
        return redirect(listaPessoaJuridica)
    
    return render(request, 'pj_confirm_delete.html', {'pessoa_juridica':pessoaJuridica})
----

=== Configurando URL para Pessoa Jurídica ===

.urls.py de cadastro
[source, python]
----
from django.urls import path
from cadastro import views

urlpatterns = [
    path('', views.index, name='index'),

    path('pessoa_juridica/lista/', views.listaPessoaJuridica, name='lista_pessoa_juridica'),
    path('pessoa_juridica/novo/', views.novoPessoaJuridica, name='novo_pessoa_juridica'),
    path('pessoa_juridica/update/<int:id>/', views.updatePessoaJuridica, name='update_pessoa_juridica'),
    path('pessoa_juridica/delete/<int:id>/', views.deletePessoaJuridica, name='delete_pessoa_juridica'),
]
----

=== Criando Templates de Pessoa Jurídica ===

==== Template para Listar Pessoa Jurídica ====

Agora o Template para a listagem de `PessoaJuridica`:

.template pj_list.html
[source, html]
----
<!-- pessoa_fisica_list.html -->

{% extends 'base.html' %}

{% block title %}Lista de Pessoa Jurídica{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h2>Lista de Pessoas Jurídicas</h2>

    <div class="mt-4 mb-2">
      <a class="btn btn-primary" href="{% url 'novo_pessoa_juridica' %}">Novo</a>
    </div>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>CNPJ</th>
          <th>Razão Social</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for pessoa_juridica in listapessoajuridica %}
          <tr>
            <td>{{ pessoa_juridica.nome }}</td>
            <td>{{ pessoa_juridica.email }}</td>
            <td>{{ pessoa_juridica.cnpj }}</td>
            <td>{{ pessoa_juridica.razao_social }}</td>
            <td>
              <a href="{% url 'update_pessoa_juridica' id=pessoa_juridica.id %}" class="btn btn-primary btn-sm">Editar</a>
              <a href="{% url 'delete_pessoa_juridica' id=pessoa_juridica.id %}" class="btn btn-danger btn-sm">Excluir</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
{% endblock %}
----

==== Template de Formulário de Pessoa Jurídica ====

Este template será utilizado para Cadastrar e Editar uma pessoa Jurídica

.pj_form.html
[source, html]
----
{% extends 'base.html' %}

{% block title %}Cadastro de Pessoa Jurídica{% endblock %}

{% block content %}
  <div class="container mt-4">
    {% if pessoa_juridica %}
      <h2>Editar Pessoa Jurídica</h2>
    {% else %}
      <h2>Adicionar Nova Pessoa Jurídica</h2>
    {% endif %}

    <form method="post" action="{% if pessoa_juridica %}{% url 'update_pessoa_juridica' id=pessoa_juridica.id %}{% else %}{% url 'novo_pessoa_juridica' %}{% endif %}">
      {% csrf_token %}
      {{ form.as_p }}

      <button type="submit" class="btn btn-primary mt-3">Salvar</button>
    </form>

    <a href="{% url 'lista_pessoa_fisica' %}" class="btn btn-secondary mt-3">Voltar para Lista</a>
  </div>
{% endblock %}
----

Com isso está finalizado todo o CRUD da classe `PessoaJuridica`.

link:https://hemmerson.github.io/django-aula/[HOME]